// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WisePriceApi.Models;

namespace WisePriceApi.Migrations
{
    [DbContext(typeof(WisePriceApiContext))]
    partial class WisePriceApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WisePriceApi.Models.Deal", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DownVotes");

                    b.Property<int>("ItemId");

                    b.Property<int>("LocationId");

                    b.Property<int>("Price");

                    b.Property<DateTime>("TimeUpdated");

                    b.Property<int>("UpVotes");

                    b.Property<int>("UserId");

                    b.HasKey("DealId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("WisePriceApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemName");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WisePriceApi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<int>("ZipCode");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WisePriceApi.Models.PinnedDeal", b =>
                {
                    b.Property<int>("PinnedDealId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DealId");

                    b.Property<int>("UserId");

                    b.HasKey("PinnedDealId");

                    b.HasIndex("DealId");

                    b.HasIndex("UserId");

                    b.ToTable("PinnedDeals");
                });

            modelBuilder.Entity("WisePriceApi.Models.PostedDeal", b =>
                {
                    b.Property<int>("PostedDealId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DealId");

                    b.Property<int>("UserId");

                    b.HasKey("PostedDealId");

                    b.HasIndex("DealId");

                    b.HasIndex("UserId");

                    b.ToTable("PostedDeals");
                });

            modelBuilder.Entity("WisePriceApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WisePriceApi.Models.Deal", b =>
                {
                    b.HasOne("WisePriceApi.Models.Item", "Item")
                        .WithMany("Deals")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WisePriceApi.Models.Location", "Location")
                        .WithMany("Deals")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WisePriceApi.Models.User")
                        .WithMany("PostedDeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WisePriceApi.Models.PinnedDeal", b =>
                {
                    b.HasOne("WisePriceApi.Models.Deal", "Deal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WisePriceApi.Models.User", "User")
                        .WithMany("PinnedDeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WisePriceApi.Models.PostedDeal", b =>
                {
                    b.HasOne("WisePriceApi.Models.Deal", "Deal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WisePriceApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
